version: "3.4"
services:

    nginx:
      image: nginx:1.12
      restart: always
      working_dir: /application
      volumes:
          - "./samplephpwebsite:/application"
          - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      ports:
       - "80:80"
      links:
        - php

    php:
      image: php:7.1-fpm
      working_dir: /application
      volumes:
        - "./samplephpwebsite:/application"
