version: "3.4"
services:

    nginx:
      image: nginx:alpine
      restart: always
      working_dir: /application
      volumes:
          - "./samplephpwebsite:/application"
          - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      ports:
       - "80:80"
      links:
        - php

    php:
      build: phpdocker/php-fpm
      working_dir: /application
      volumes:
        - "./samplephpwebsite:/application"

    jenkins:
      build: phpdocker/jenkins
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "./phpdocker/jenkins/jenkins_home:/var/jenkins_home"
      ports:
        - "8081:8080"
