version: "3.4"
services:

    nginx:
      image: nginx:1.12
      restart: always
      working_dir: /application
      volumes:
        - "./samplephpwebsite:/application"
        - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      ports:
        - "80:80"
      links:
        - php

    php:
      build: ./phpdocker/php-fpm
      working_dir: /application
      volumes:
        - "./samplephpwebsite:/application"
      links:
        - db

    db:
      image: mariadb:10.1
      restart: always
      volumes:
        - "./phpdocker/mysql:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: php_user
        MYSQL_PASSWORD: sdrugntqqsciur
        MYSQL_DATABASE: db
      ports:
        - "8889:3306"
